name: CI pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4#
      
      - name: Install grype
        run : |
          curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b /usr/local/bin
      
      - name: Run Grype
        run: |
          ./usr/local/bin/grype dir:. --fail-on high 
      
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      
      - name: build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o app .

      - name: build docker images
        if: github.event_name == 'push'
        run: |
          docker build -t myapp:latest . 